---
- name: "Install latest stable microk8s snap"
  snap:
      name: microk8s
      channel: latest
      classic: "yes"
      state: present
  notify:
      - Enable snapd
      - Start snapd
      - Enable microk8s addons

- name: "Create alias k"
  command: snap alias microk8s.kubectl k
  register: k_alias
  changed_when: k_alias.stdout.find('Added') != -1

- name: "Create alias kubectl"
  command: snap alias microk8s.kubectl kubectl
  register: kubectl_alias
  changed_when: kubectl_alias.stdout.find('Added') != -1

- name: "Create alias helm"
  command: snap alias microk8s.helm3 helm
  register: helm_alias
  changed_when: helm_alias.stdout.find('Added') != -1
